### ISSUE TITLE
转换成PDF出错

### ISSUE THREAD

**Issue by MingHe9527** [flutterchina/flutter-in-action#9]
在使用gitbook pdf命令将电子书导出成PDF的过程中报错
{ Error: Cannot find module 'prismjs/components/prism-shell.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireSyntax (/Users/minghe/Workspaces/GitHub/flutter-in-action/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/Users/minghe/Workspaces/GitHub/flutter-in-action/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/Users/minghe/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /Users/minghe/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /Users/minghe/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /Users/minghe/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
Failed to load prism syntax: shell
大概就是这样的错误，多次出现，不知道是不是我自己操作的问题。

**Comment by dongfg** [comment]
也遇到这个问题了，看了下是md里 *```shell* 这个写法的问题，自己本地替换下就可以了
```bash
find docs  -type f -name *.md | xargs sed -i '' -e $'s/\`\`\`shell/\`\`\`bash/g'
```

**Comment by Akateason** [comment]
Mac gitbook 3.2.3 

TypeError: this element does not have children or attributes
